server:
  port: 10010
spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/rank?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: company # 路由标示，必须唯一
          uri: lb://company # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/company/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: oaa # 路由标示，必须唯一
          uri: lb://oaa # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/oaa/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: system # 路由标示，必须唯一
          uri: lb://system # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/system/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: table # 路由标示，必须唯一
          uri: lb://table # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/table/** # 路径断言，判断路径是否是以/user开头，如果是则符合
feign:
  hystrix:
    enabled: true
    #开启feign断路器 依赖hystrix包
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
