server:
  port: 9009
spring:
  application:
    name: table
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/rank?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848