server:
  port: 9009
spring:
  application:
    name: table
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 37FCRrSDzBawsynj
    url: jdbc:mysql://47.96.236.125:3306/rank
    username: rank
  redis:
    host: 47.96.236.125
    port: 6379
    password: gaoyifeng
  cloud:
    nacos:
      discovery:
        server-addr: 47.96.236.125:8848